import { StrictMode, memo, useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { io, type Socket } from 'socket.io-client';
import { createRoot } from 'react-dom/client';
import './styles.css';

type User={id:string;username:string;score:number;wins:number;losses:number;matchesPlayed:number;winRate?:number;role?:'player'|'admin';isSuspended?:boolean};
type Settings={audioEnabled:boolean;sfxVolume:number;animationsEnabled:boolean;notificationsEnabled:boolean};
type RoomPlayer={userId:string;username:string;isHost:boolean;ready:boolean;status:string;joinedAt:string};
type Room={code:string;hostUserId:string;visibility:'public'|'private';maxPlayers:number;status:'waiting'|'starting';createdAt:string;players:RoomPlayer[]};
type Card={id:string;type:'number'|'warning'|'foul'|'reverse'|'switch'|'penalty'|'red';teamId?:string;number?:number;playerId?:string};
type PlayerAsset={id:string;name:string;teamId:string;number:number;image:string;goalkeeper:boolean;retired:boolean};
type Team={id:string;name:string;color:string;logo:string;flag:string};
type GameState={status:string;currentTeamId:string;currentNumber?:number;currentPlayerId:string;direction:1|-1;drawCount:number;discardTop?:Card;players:any[];penalty?:{attackerId:string;defenderId:string;phase:string;deadlineAt?:number;chosenTeamId?:string};switchState?:{playerId:string;targetPlayerId:string;phase:string;ownCardId?:string;targetHand?:Card[]};skipNext:boolean;version:number;winnerIds:string[];finishedRanking:any[]};
const API=import.meta.env.VITE_API_URL || 'http://localhost:3001';
const teams:Team[]=[{id:'brazil',name:'Brazil',color:'#2d7a3e',logo:'/assets/teams/brazil.svg',flag:'/assets/flags/brazil.svg'},{id:'argentina',name:'Argentina',color:'#75aadb',logo:'/assets/teams/argentina.svg',flag:'/assets/flags/argentina.svg'},{id:'france',name:'France',color:'#1d4ed8',logo:'/assets/teams/france.svg',flag:'/assets/flags/france.svg'},{id:'portugal',name:'Portugal',color:'#c8102e',logo:'/assets/teams/portugal.svg',flag:'/assets/flags/portugal.svg'}];
const players:PlayerAsset[]=Array.from({length:4},(_,ti)=>teams[ti]).flatMap(t=>Array.from({length:10},(_,n)=>({id:`${t.id}-${n}`,name:n===0?({brazil:'Ronaldo Nazário',argentina:'Retired Player',france:'Retired Player',portugal:'Retired Player'} as any)[t.id]:`${t.name} Player ${n}`,teamId:t.id,number:n,image:'/assets/players/placeholder.svg',goalkeeper:n===1,retired:n===0})));
function playLocalSfx(kind:'play'|'draw'|'warning'|'win') { try { const raw=localStorage.getItem('game_on_settings'); const st=raw?JSON.parse(raw):{audioEnabled:true,sfxVolume:.65}; if(!st.audioEnabled||!st.sfxVolume)return; const Ctx=(window.AudioContext||((window as any).webkitAudioContext)); if(!Ctx)return; const ctx=new Ctx(); const osc=ctx.createOscillator(); const gain=ctx.createGain(); const freq=kind==='win'?660:kind==='draw'?260:kind==='warning'?430:520; osc.frequency.value=freq; osc.type='sine'; gain.gain.value=Math.min(.08,Number(st.sfxVolume)*.1); osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.09);osc.onended=()=>ctx.close(); } catch {} }
async function api(path:string, options:RequestInit={}){const r=await fetch(API+path,{credentials:'include',headers:{'content-type':'application/json',...(options.headers||{})},...options});const data=r.status===204?null:await r.json().catch(()=>({error:'Unexpected server response'}));if(!r.ok)throw new Error(data?.error||'Request failed');return data;}

function App(){
 const [view,setView]=useState<'home'|'login'|'register'|'profile'|'history'|'leaderboard'|'rooms'|'game'|'friends'|'notifications'|'settings'|'admin'>('home');const [game,setGame]=useState<GameState|null>(null);const [room,setRoom]=useState<Room|null>(null);const [roomCode,setRoomCode]=useState('');const [user,setUser]=useState<User|null>(null);const [error,setError]=useState('');const [unread,setUnread]=useState(0);const [settings,setSettings]=useState<Settings>({audioEnabled:true,sfxVolume:.65,animationsEnabled:true,notificationsEnabled:true});
 useEffect(()=>{api('/api/auth/me').then(x=>setUser(x.user)).catch(()=>{});},[]);
 useEffect(()=>{if(!user)return;api('/api/settings').then(x=>{setSettings(x.settings);localStorage.setItem('game_on_settings',JSON.stringify(x.settings));}).catch(()=>{});const load=()=>api('/api/notifications?limit=50').then(x=>setUnread((x.rows||[]).filter((n:any)=>!n.readAt).length)).catch(()=>{});load();const t=setInterval(load,15000);return()=>clearInterval(t);},[user]);
 useEffect(()=>{if(!user)return;const socket:Socket=io(API,{withCredentials:true});socket.on('game:state',(s:GameState)=>setGame(s));socket.on('room:state',(r:Room)=>setRoom(r));socket.on('game:reconnectToken',(payload:any)=>{if(payload?.matchId&&payload?.token){localStorage.setItem('game_on_reconnect',JSON.stringify(payload));}});socket.on('connect',()=>{socket.emit('room:subscribe');const raw=localStorage.getItem('game_on_reconnect');if(raw){try{const saved=JSON.parse(raw);socket.emit('game:reconnect',saved,(r:any)=>{if(!r?.ok&&r?.code==='INVALID_RECONNECT_TOKEN')localStorage.removeItem('game_on_reconnect');});}catch{localStorage.removeItem('game_on_reconnect');}}});return()=>{socket.disconnect();};},[user]);
 const logout=async()=>{await api('/api/auth/logout',{method:'POST'});setUser(null);setRoom(null);setGame(null);setView('home');};
 const refreshRoom=async()=>{const x=await api('/api/rooms/me');setRoom(x.room);};
 const createRoomAction=async()=>{const x=await api('/api/rooms',{method:'POST',body:JSON.stringify({visibility:'private',maxPlayers:4})});setRoom(x.room);setView('rooms');};
 const joinRoomAction=async()=>{try{const x=await api('/api/rooms/join',{method:'POST',body:JSON.stringify({code:roomCode})});setRoom(x.room);setError('');}catch(e){setError(e instanceof Error?e.message:'Unable to join');}};
 const readyAction=async()=>{const me=room?.players.find((p:RoomPlayer)=>p.userId===user?.id);const x=await api('/api/rooms/ready',{method:'POST',body:JSON.stringify({ready:!me?.ready})});setRoom(x.room);};
 const leaveRoomAction=async()=>{const x=await api('/api/rooms/leave',{method:'POST'});setRoom(x.room);};
 const startRoomAction=async()=>{const socket=io(API,{withCredentials:true});await new Promise<void>((resolve,reject)=>{socket.on('connect_error',()=>reject(new Error('Socket connection failed')));socket.on('connect',()=>socket.emit('room:subscribe'));socket.emit('game:start',{requestId:crypto.randomUUID()},(r:any)=>r?.ok?resolve():reject(new Error(r?.message||r?.code||'Unable to start game')));});socket.disconnect();setView('game');};
 const submit=async(type:'login'|'register',e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError('');const f=new FormData(e.currentTarget);try{const body=type==='login'?{username:f.get('username'),password:f.get('password')}:{username:f.get('username'),password:f.get('password'),confirmPassword:f.get('confirmPassword')};const x=await api('/api/auth/'+type,{method:'POST',body:JSON.stringify(body)});setUser(x.user);setView('profile');}catch(err){setError(err instanceof Error?err.message:'Something went wrong');}};
 if(view==='login'||view==='register')return <Auth type={view} error={error} onSubmit={submit} onBack={()=>{setError('');setView('home')}}/>;
 if(view==='rooms')return <RoomLobby user={user!} room={room} code={roomCode} setCode={setRoomCode} create={createRoomAction} join={joinRoomAction} refresh={refreshRoom} ready={readyAction} leave={leaveRoomAction} start={startRoomAction} back={()=>setView('home')} error={error}/>;
 if(view==='game')return <GameView apiUrl={API} user={user!} game={game} back={()=>{setView('rooms');setGame(null)}}/>;
 if(view==='profile')return <ProfilePage user={user!} onBack={()=>setView('home')} onHistory={()=>setView('history')} />;
 if(view==='history')return <HistoryPage onBack={()=>setView('profile')}/>;
 if(view==='leaderboard')return <LeaderboardPage onBack={()=>setView('home')}/>;
 if(view==='friends')return <FriendsPage onBack={()=>setView('home')}/>;
 if(view==='notifications')return <NotificationsPage onBack={()=>setView('home')} onUnreadChange={setUnread}/>;
 if(view==='settings')return <SettingsPage settings={settings} setSettings={setSettings} onBack={()=>setView('home')}/>;
 if(view==='admin')return <AdminPage onBack={()=>setView('home')}/>;
 return <main className="app"><section className="landing"><header><div className="brand"><img className="brand-logo" src="/assets/game-on-logo.svg" alt="GAME ON"/><span className="sr-only">GAME ON</span></div><nav className="top-nav"><button className="ghost" onClick={()=>setView('leaderboard')}>Leaderboard</button>{user?<><button className="ghost" onClick={()=>setView('friends')}>Friends</button><button className="ghost" onClick={()=>setView('notifications')}>🔔{unread>0?` ${unread}`:''}</button><button className="ghost" onClick={()=>setView('settings')}>Settings</button>{user.role==='admin'&&<button className="ghost admin-link" onClick={()=>setView('admin')}>Admin</button>}<button className="ghost" onClick={()=>setView('profile')}>Profile</button><button className="ghost" onClick={logout}>Logout</button></>:<button className="ghost" onClick={()=>setView('login')}>Login</button>}</nav></header><div className="hero-copy"><span className="eyebrow">ONLINE FOOTBALL CARD BATTLE</span><h1>GAME <em>ON</em> ⚽</h1><h2>FOOTBALL CARD BATTLE</h2><p>مش مجرد كروت... دي ماتش كامل.</p><div className="hero-buttons">{user?<button className="primary big" onClick={()=>setView('rooms')}>Play Online <span>→</span></button>:<button className="primary big" onClick={()=>setView('register')}>Create Account <span>→</span></button>}<button className="secondary big" onClick={()=>setView('rooms')}>Create / Join Room</button></div></div><div className="feature-grid"><Feature icon="108" label="Cards"/><Feature icon="4" label="Players"/><Feature icon="5s" label="Penalty Challenge"/></div></section></main>;
}
function Feature({icon,label}:{icon:string;label:string}){return <div className="feature"><strong>{icon}</strong><span>{label}</span></div>}

function ProfilePage({user,onBack,onHistory}:{user:User;onBack:()=>void;onHistory:()=>void}){
 const winRate=user.winRate ?? (user.matchesPlayed?Math.round(user.wins/user.matchesPlayed*1000)/10:0);
 return <main className="app center"><section className="data-panel glass"><div className="panel-head"><div><span className="eyebrow">PLAYER PROFILE</span><h3>{user.username}</h3></div><button className="ghost" onClick={onBack}>← Home</button></div><div className="stats-grid"><Stat label="Score" value={user.score}/><Stat label="Matches" value={user.matchesPlayed}/><Stat label="Wins" value={user.wins}/><Stat label="Losses" value={user.losses}/><Stat label="Win Rate" value={`${winRate}%`}/></div><button className="primary full" onClick={onHistory}>View Match History</button></section></main>
}
function Stat({label,value}:{label:string;value:string|number}){return <div className="stat-card"><span>{label}</span><strong>{value}</strong></div>}
function HistoryPage({onBack}:{onBack:()=>void}){
 const [data,setData]=useState<any>(null); const [error,setError]=useState('');
 useEffect(()=>{api('/api/matches?page=1&pageSize=30').then(setData).catch(e=>setError(e instanceof Error?e.message:'Unable to load history'));},[]);
 return <main className="app center"><section className="data-panel glass"><div className="panel-head"><div><span className="eyebrow">MATCH HISTORY</span><h3>Previous Matches</h3></div><button className="ghost" onClick={onBack}>← Profile</button></div>{error&&<div className="error">{error}</div>}{!data&&!error?<div className="loading-state">Loading…</div>:data?.rows?.length===0?<div className="empty-state">No matches yet.</div>:<div className="history-list">{data?.rows?.map((m:any)=><div className="history-row" key={m.id}><div><strong>{m.players}</strong><small>{m.finishedAt?new Date(m.finishedAt).toLocaleString():'In progress'}</small></div><div><b>#{m.rank ?? '—'}</b><span>+{m.scoreEarned}</span></div><div><small>{m.cardsRemaining} cards · 🟨 {m.warnings} · 🟥 {m.reds} · Σ {m.numberSum}</small></div></div>)}</div>}</section></main>
}
function LeaderboardPage({onBack}:{onBack:()=>void}){
 const [data,setData]=useState<any>(null); const [error,setError]=useState('');
 useEffect(()=>{api('/api/leaderboard?page=1&pageSize=50').then(setData).catch(e=>setError(e instanceof Error?e.message:'Unable to load leaderboard'));},[]);
 return <main className="app center"><section className="data-panel glass"><div className="panel-head"><div><span className="eyebrow">LEADERBOARD</span><h3>Top Players</h3></div><button className="ghost" onClick={onBack}>← Home</button></div>{error&&<div className="error">{error}</div>}{!data&&!error?<div className="loading-state">Loading…</div>:<div className="leaderboard-list"><div className="lb-row lb-head"><span>#</span><span>Player</span><span>Score</span><span>W</span><span>M</span><span>WR</span></div>{data?.rows?.map((r:any,i:number)=><div className="lb-row" key={r.id}><b>{i+1+(data.page-1)*data.pageSize}</b><strong>{r.username}</strong><span>{r.score}</span><span>{r.wins}</span><span>{r.matchesPlayed}</span><span>{r.winRate}%</span></div>)}</div>}</section></main>
}
function FriendsPage({onBack}:{onBack:()=>void}){
 const [data,setData]=useState<any>({friends:[],incoming:[],outgoing:[]});const [q,setQ]=useState('');const [results,setResults]=useState<any[]>([]);const [error,setError]=useState('');
 const load=()=>api('/api/friends').then(setData).catch(e=>setError(e instanceof Error?e.message:'Unable to load friends'));
 useEffect(()=>{load();},[]);
 const search=async()=>{try{const x=await api('/api/users/search?q='+encodeURIComponent(q));setResults(x.rows||[]);setError('');}catch(e){setError(e instanceof Error?e.message:'Search failed');}};
 const add=async(username:string)=>{try{await api('/api/friends/request',{method:'POST',body:JSON.stringify({username})});setError('Friend request sent.');await load();}catch(e){setError(e instanceof Error?e.message:'Unable to send request');}};
 const respond=async(friendshipId:string,accept:boolean)=>{try{await api('/api/friends/respond',{method:'POST',body:JSON.stringify({friendshipId,accept})});await load();}catch(e){setError(e instanceof Error?e.message:'Unable to respond');}};
 return <main className="app center"><section className="data-panel glass"><div className="panel-head"><div><span className="eyebrow">SOCIAL</span><h3>Friends</h3></div><button className="ghost" onClick={onBack}>← Home</button></div><div className="join"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search username" maxLength={24}/><button className="primary" onClick={search}>Search</button></div>{error&&<div className="error">{error}</div>}{results.length>0&&<div className="history-list">{results.map((r:any)=><div className="history-row" key={r.id}><div><strong>{r.username}</strong><small>Score {r.score}</small></div><button className="secondary" disabled={!!r.friendship} onClick={()=>add(r.username)}>{r.friendship==='accepted'?'Friends':r.friendship==='outgoing'?'Pending':r.friendship==='incoming'?'Incoming':'Add Friend'}</button></div>)}</div>}<h4>Friend Requests</h4>{data.incoming?.map((r:any)=><div className="history-row" key={r.id}><div><strong>{r.username}</strong><small>Wants to connect</small></div><div className="actions"><button className="primary" onClick={()=>respond(r.id,true)}>Accept</button><button className="ghost" onClick={()=>respond(r.id,false)}>Decline</button></div></div>)}<h4>Your Friends</h4>{data.friends?.length?data.friends.map((f:any)=><div className="history-row" key={f.id}><div><strong>{f.username}</strong><small>Score {f.score} · {f.wins} wins</small></div></div>):<div className="empty-state">No friends yet.</div>}</section></main>
}
function AdminPage({onBack}:{onBack:()=>void}){
 const [dash,setDash]=useState<any>(); const [users,setUsers]=useState<any[]>([]); const [matches,setMatches]=useState<any[]>([]); const [audit,setAudit]=useState<any[]>([]); const [q,setQ]=useState(''); const [error,setError]=useState('');
 const load=async()=>{try{const [d,u,m,a]=await Promise.all([api('/api/admin/dashboard'),api('/api/admin/users?pageSize=50'),api('/api/admin/matches?pageSize=25'),api('/api/admin/audit?pageSize=25')]);setDash(d);setUsers(u.rows||[]);setMatches(m.rows||[]);setAudit(a.rows||[]);}catch(e){setError(e instanceof Error?e.message:'Admin access required');}};
 useEffect(()=>{load();},[]);
 const search=async()=>{try{const x=await api('/api/admin/users?pageSize=50&q='+encodeURIComponent(q));setUsers(x.rows||[]);}catch(e){setError(e instanceof Error?e.message:'Search failed');}};
 const action=async(path:string,body:any)=>{try{await api(path,{method:'PATCH',body:JSON.stringify(body)});await load();}catch(e){setError(e instanceof Error?e.message:'Action failed');}};
 return <main className="app center"><section className="data-panel glass admin-panel"><div className="panel-head"><div><span className="eyebrow">SECURE CONTROL ROOM</span><h3>Admin Panel</h3></div><button className="ghost" onClick={onBack}>← Home</button></div>{error&&<div className="error">{error}</div>}<div className="admin-stats">{dash&&Object.entries(dash).map(([k,v])=><div className="stat-card" key={k}><strong>{String(v)}</strong><small>{k.replace(/([A-Z])/g,' $1')}</small></div>)}</div><h4>Users</h4><div className="join"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search username"/><button className="primary" onClick={search}>Search</button></div><div className="history-list">{users.map(u=><div className="history-row" key={u.id}><div><strong>{u.username} {u.role==='admin'?'🛡️':''}</strong><small>{u.score} score · {u.wins}W / {u.losses}L · {u.isSuspended?'SUSPENDED':'active'}</small></div><div className="actions"><button className="secondary" onClick={()=>action('/api/admin/users/'+u.id+'/role',{role:u.role==='admin'?'player':'admin'})}>{u.role==='admin'?'Make player':'Make admin'}</button><button className="ghost" onClick={()=>action('/api/admin/users/'+u.id+'/suspension',{suspended:!u.isSuspended})}>{u.isSuspended?'Unsuspend':'Suspend'}</button></div></div>)}</div><h4>Recent Matches</h4><div className="history-list">{matches.map(m=><div className="history-row" key={m.id}><div><strong>{m.status}</strong><small>{m.id.slice(0,8)} · {m.playerCount} players · {new Date(m.createdAt).toLocaleString()}</small></div></div>)}</div><h4>Admin Audit</h4><div className="history-list">{audit.map(a=><div className="history-row" key={a.id}><div><strong>{a.action}</strong><small>{a.adminUsername} · {new Date(a.createdAt).toLocaleString()}</small></div></div>)}</div></section></main>
}
function NotificationsPage({onBack,onUnreadChange}:{onBack:()=>void;onUnreadChange:(n:number)=>void}){
 const [rows,setRows]=useState<any[]>([]);const load=()=>api('/api/notifications?limit=50').then(x=>{setRows(x.rows||[]);onUnreadChange((x.rows||[]).filter((n:any)=>!n.readAt).length);});useEffect(()=>{load().catch(()=>{});},[]);
 const read=async(id:string)=>{await api('/api/notifications/'+id+'/read',{method:'POST'});await load();};const all=async()=>{await api('/api/notifications/read-all',{method:'POST'});await load();};
 return <main className="app center"><section className="data-panel glass"><div className="panel-head"><div><span className="eyebrow">INBOX</span><h3>Notifications</h3></div><div className="actions"><button className="ghost" onClick={all}>Mark all read</button><button className="ghost" onClick={onBack}>← Home</button></div></div>{rows.length?rows.map(n=><button className={n.readAt?'notification-row read':'notification-row'} key={n.id} onClick={()=>read(n.id)}><strong>{n.title}</strong><span>{n.body}</span><small>{new Date(n.createdAt).toLocaleString()}</small></button>):<div className="empty-state">You're all caught up.</div>}</section></main>
}
function SettingsPage({settings,setSettings,onBack}:{settings:Settings;setSettings:(s:Settings)=>void;onBack:()=>void}){
 const save=async(patch:Partial<Settings>)=>{try{const x=await api('/api/settings',{method:'PATCH',body:JSON.stringify(patch)});setSettings(x.settings);localStorage.setItem('game_on_settings',JSON.stringify(x.settings));}catch{}};
 const toggle=(key:'audioEnabled'|'animationsEnabled'|'notificationsEnabled')=>save({[key]:!settings[key]});
 return <main className="app center"><section className="data-panel glass settings-panel"><div className="panel-head"><div><span className="eyebrow">PLAYER SETTINGS</span><h3>Game Preferences</h3></div><button className="ghost" onClick={onBack}>← Home</button></div><div className="setting-row"><div><strong>Sound effects</strong><small>Use lightweight local game sounds.</small></div><button className="secondary" onClick={()=>toggle('audioEnabled')}>{settings.audioEnabled?'ON':'OFF'}</button></div><div className="setting-row"><div><strong>SFX volume</strong><small>Adjust match sound level.</small></div><input type="range" min="0" max="1" step="0.05" value={settings.sfxVolume} onChange={e=>save({sfxVolume:Number(e.target.value)})}/><span>{Math.round(settings.sfxVolume*100)}%</span></div><div className="setting-row"><div><strong>Animations</strong><small>Keep card and modal motion enabled.</small></div><button className="secondary" onClick={()=>toggle('animationsEnabled')}>{settings.animationsEnabled?'ON':'OFF'}</button></div><div className="setting-row"><div><strong>Notifications</strong><small>Allow social notification inbox updates.</small></div><button className="secondary" onClick={()=>toggle('notificationsEnabled')}>{settings.notificationsEnabled?'ON':'OFF'}</button></div><div className="muted">Settings are saved to your account.</div></section></main>
}

function Auth({type,error,onSubmit,onBack}:{type:'login'|'register';error:string;onSubmit:any;onBack:()=>void}){return <main className="app center"><motion.form initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} className="auth glass" onSubmit={e=>onSubmit(type,e)}><button type="button" className="ghost left" onClick={onBack}>← Back</button><div className="brand"><img className="brand-logo" src="/assets/game-on-logo.svg" alt="GAME ON"/><span className="sr-only">GAME ON</span></div><h3>{type==='login'?'Welcome back':'Create your account'}</h3><p className="muted">{type==='login'?'Enter the pitch.':'Create your player identity.'}</p><label>Username<input name="username" minLength={3} maxLength={24} required autoComplete="username"/></label><label>Password<input name="password" type="password" minLength={8} maxLength={128} required autoComplete={type==='login'?'current-password':'new-password'}/></label>{type==='register'&&<label>Confirm password<input name="confirmPassword" type="password" minLength={8} maxLength={128} required autoComplete="new-password"/></label>}{error&&<div className="error" role="alert">{error}</div>}<button className="primary" type="submit">{type==='login'?'Login':'Create Account'}</button></motion.form></main>}
function RoomLobby({user,room,code,setCode,create,join,refresh,ready,leave,start,back,error}:{user:User;room:Room|null;code:string;setCode:(v:string)=>void;create:()=>Promise<void>;join:()=>Promise<void>;refresh:()=>Promise<void>;ready:()=>Promise<void>;leave:()=>Promise<void>;start:()=>Promise<void>;back:()=>void;error:string}){useEffect(()=>{if(!room)refresh().catch(()=>{});},[]);return <main className="app center"><section className="room-panel glass"><div className="panel-head"><div><span className="eyebrow">LOBBY / ROOMS</span><h3>{room?'Room '+room.code:'Find a match'}</h3></div><button className="ghost" onClick={back}>← Home</button></div>{!room?<><button className="primary big full" onClick={create}>＋ Create Private Room</button><div className="divider"><span>OR</span></div><div className="join"><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} maxLength={6} placeholder="ROOM CODE"/><button className="secondary" onClick={join}>Join Room</button></div>{error&&<div className="error">{error}</div>}</>:<><div className="room-meta"><span>{room.players.length}/{room.maxPlayers} players</span><span className="live-dot">● {room.status}</span></div><div className="room-players">{room.players.map(p=><div className="player-row" key={p.userId}><div className="avatar">{p.username.slice(0,1).toUpperCase()}</div><div><strong>{p.username}{p.isHost?' 👑':''}</strong><small>{p.ready?'READY':'WAITING'}</small></div><span className={p.ready?'status-ready':'status-wait'}>{p.ready?'✓':'•'}</span></div>)}</div><div className="actions"><button className="secondary" onClick={ready}>{room.players.find(p=>p.userId===user.id)?.ready?'Unready':'Ready Up'}</button>{room.hostUserId===user.id&&<button className="primary" onClick={start}>Start Match</button>}<button className="ghost" onClick={leave}>Leave</button></div></>}</section></main>}

function GameView({apiUrl,user,game,back}:{apiUrl:string;user:User;game:GameState|null;back:()=>void}){
 const [socket,setSocket]=useState<Socket|null>(null);const [local,setLocal]=useState<GameState|null>(game);const [notice,setNotice]=useState('');const [now,setNow]=useState(Date.now());const [selectedOwn,setSelectedOwn]=useState<string>();
 const frame=useRef<number|undefined>(undefined);const pendingState=useRef<GameState|null>(null);const socketRef=useRef<Socket|null>(null);
 useEffect(()=>{const s=io(apiUrl,{withCredentials:true,transports:['websocket','polling'],upgrade:true,reconnection:true,reconnectionAttempts:Infinity,reconnectionDelay:500,reconnectionDelayMax:5000});socketRef.current=s;setSocket(s);
   const publish=(x:GameState)=>{pendingState.current=x;if(frame.current!==undefined)return;frame.current=requestAnimationFrame(()=>{frame.current=undefined;const next=pendingState.current;pendingState.current=null;if(next)setLocal(next);});};
   s.on('game:state',publish);s.on('game:error',(e:any)=>setNotice(e?.message||'Action rejected'));
   s.on('game:reconnectToken',(payload:any)=>{if(payload?.matchId&&payload?.token)localStorage.setItem('game_on_reconnect',JSON.stringify(payload));});
   s.on('connect',()=>{s.emit('room:subscribe');const raw=localStorage.getItem('game_on_reconnect');if(raw){try{const saved=JSON.parse(raw);s.emit('game:reconnect',saved,(r:any)=>{if(!r?.ok&&r?.code==='INVALID_RECONNECT_TOKEN')localStorage.removeItem('game_on_reconnect');});}catch{localStorage.removeItem('game_on_reconnect');}}});
   return()=>{if(frame.current!==undefined)cancelAnimationFrame(frame.current);s.removeAllListeners();s.disconnect();socketRef.current=null;};
 },[apiUrl]);
 useEffect(()=>setLocal(game),[game]);
 useEffect(()=>{if(!local?.penalty?.deadlineAt)return;const t=window.setInterval(()=>setNow(Date.now()),100);return()=>window.clearInterval(t)},[local?.penalty?.deadlineAt]);
 const send=useCallback((type:string,extra:any={})=>{const s=socketRef.current;if(!s)return;setNotice('');if(type==='playCard')playLocalSfx('play');if(type==='drawCard')playLocalSfx('draw');s.emit('game:action',{requestId:crypto.randomUUID(),action:{type,...extra}},(r:any)=>{if(r&&!r.ok)setNotice(r.message||r.code||'Action rejected');});},[]);
 if(!local)return <main className="app center"><section className="glass loading"><div className="spinner"/><h3>Connecting to the match…</h3><p className="muted">Server-authoritative game state is loading.</p></section></main>;
 const me=local.players.find(p=>p.id===user.id);const top=local.discardTop;const team=teams.find(t=>t.id===local.currentTeamId);const penalty=local.penalty;const switchState=local.switchState;const countdown=penalty?.deadlineAt?Math.max(0,(penalty.deadlineAt-now)/1000):0;const isTurn=local.currentPlayerId===user.id;
 const playable=(c:Card)=>c.type==='penalty'||c.type==='red'||c.type==='number'?(c.type!=='number'||c.number===local.currentNumber||c.teamId===local.currentTeamId||c.number===0&&c.teamId===local.currentTeamId):c.teamId===local.currentTeamId;
 const opponent=useMemo(()=>local.players.filter(p=>p.id!==user.id),[local.players,user.id]);
 const goalkeeper=useMemo(()=>me?.hand?.find((x:Card)=>x.type==='number'&&players.find(a=>a.id===x.playerId)?.goalkeeper),[me?.hand]);
 return <main className="game-app"><header className="game-top"><button className="ghost touch-target" onClick={back}>← Lobby</button><div className="game-brand"><img className="game-brand-logo" src="/assets/game-on-logo.svg" alt="GAME ON"/></div><div className="match-pill"><i/> LIVE · {local.version}</div></header><section className="pitch-shell"><div className="pitch"><div className="center-circle"/><div className="center-line"/><div className="goal top-goal"/><div className="goal bottom-goal"/>
   <div className="pitch-title"><span className="eyebrow">CURRENT TEAM</span><strong style={{color:team?.color||'white'}}>{team?.name||local.currentTeamId}</strong><small>{local.currentNumber!==undefined?`Number ${local.currentNumber}`:'Choose your play'}</small></div>
   <div className="pile-area"><div className="pile draw"><span>DRAW</span><strong>{local.drawCount}</strong><small>cards</small></div><div className="discard-wrap"><span>IN PLAY</span>{top?<GameCard card={top} asset={players.find(p=>p.id===top.playerId)} team={teams.find(t=>t.id===top.teamId)} playable={false} onClick={()=>{}}/>:<div className="empty-card">START</div>}</div></div>
   {opponent.map((p:any,i:number)=><Opponent key={p.id} p={p} position={i} active={p.id===local.currentPlayerId}/>) }
   <div className="me-slot"><div className={isTurn?'turn-ring me-info':'me-info'}><div className="avatar big-avatar">{user.username.slice(0,1).toUpperCase()}</div><div><strong>{user.username} {isTurn?'⚡':''}</strong><small>{me?.cardCount||0} cards · 🟨 {me?.warnings||0} · 🟥 {me?.reds||0}</small></div>{me?.goalkeeper&&<div className="keeper-mini">🧤</div>}</div></div>
  </div>
  <div className="hand-dock"><div className="hand-header"><div><span className="eyebrow">YOUR HAND</span><strong>{me?.hand?.length||0} CARDS</strong></div>{isTurn&&<span className="your-turn">YOUR TURN</span>}</div><div className="hand-scroll">{me?.hand?.map((c:Card)=><HandCard key={c.id} card={c} playable={playable(c)} isTurn={isTurn} onPlay={send}/>)}</div><div className="action-bar">{isTurn&&<button className="primary touch-target" onClick={()=>send('drawCard')}>Draw Card</button>}{me?.hand?.some((c:Card)=>c.type==='switch')&&isTurn&&<button className="secondary touch-target" onClick={()=>setNotice('Play Switch, then choose the exchange.')}>Switch</button>}{goalkeeper&&<button className="ghost touch-target" onClick={()=>send('placeGoalkeeper',{cardId:goalkeeper.id})}>🧤 Goalkeeper</button>}<AnimatePresence>{notice&&<motion.span initial={{opacity:0,x:10}} animate={{opacity:1,x:0}} className="toast" role="status">{notice}</motion.span>}</AnimatePresence></div></div>
  {penalty&&<PenaltyModal penalty={penalty} userId={user.id} teams={teams} countdown={countdown} send={send}/>} {switchState&&<SwitchModal state={switchState} userId={user.id} players={local.players} me={me} send={send} selectedOwn={selectedOwn} setSelectedOwn={setSelectedOwn}/>} {local.status==='finished'&&<ResultOverlay state={local}/>} 
 </section></main>
}
const HandCard=memo(function HandCard({card,playable,isTurn,onPlay}:{card:Card;playable:boolean;isTurn:boolean;onPlay:(type:string,extra?:any)=>void}){return <GameCard card={card} asset={players.find(p=>p.id===card.playerId)} team={teams.find(t=>t.id===card.teamId)} playable={isTurn&&playable} onClick={()=>{if(isTurn&&playable)onPlay('playCard',{cardId:card.id})}}/>});
const Opponent=memo(function Opponent({p,position,active}:{p:any;position:number;active:boolean}){return <motion.div initial={{opacity:0,y:-10}} animate={{opacity:1,y:0}} className={`opponent opponent-${position} ${active?'active-opponent':''}`}><div className="avatar">{p.username.slice(0,1).toUpperCase()}</div><div><strong>{p.username}{active?' ⚡':''}</strong><small>{p.cardCount} cards</small><span>🟨 {p.warnings} · 🟥 {p.reds} {p.goalkeeper?'· 🧤':''}</span></div></motion.div>});
const GameCard=memo(function GameCard({card,asset,team,hidden,playable,onClick}:{card:Card;asset?:PlayerAsset;team?:Team;hidden?:boolean;playable:boolean;onClick:()=>void}){if(hidden)return <div className="card-back"><span>GAME<br/>ON</span>⚽</div>;const labels:any={warning:'WARNING',foul:'FOUL',reverse:'REVERSE',switch:'SWITCH',penalty:'PENALTY',red:'RED CARD'};return <motion.button whileHover={playable?{y:-14,rotate:-1,scale:1.03}:undefined} whileTap={playable?{scale:.97}:undefined} className={`game-card ${card.type} ${playable?'playable':'dimmed'}`} style={{'--team':team?.color||'#22d3ee'} as any} disabled={!playable} onClick={onClick}><div className="card-gloss"/><div className="card-top"><span>{card.type==='number'?team?.name||'TEAM':'GAME ON'}</span><span>{card.type==='number'?(card.number===0?'0':card.number):labels[card.type]}</span></div>{card.type==='number'?<><div className="player-art"><img src={asset?.image||'/assets/players/placeholder.svg'} alt=""/><span className="player-number">{card.number}</span></div><div className="card-name">{asset?.name||'Player'}</div><div className="card-foot">{card.number===0?<b>RETIRED</b>:<><span>{team?.name}</span>{asset?.goalkeeper&&<span>🧤</span>}</>}</div></>:<div className="function-face"><strong>{card.type==='penalty'?'⚽':card.type==='red'?'🟥':card.type==='warning'?'🟨':card.type==='foul'?'⚠️':card.type==='reverse'?'↔':'⇄'}</strong><span>{labels[card.type]}</span><small>{card.type==='warning'?'+2 +WARNING':card.type==='red'?'WILD +4':card.type==='penalty'?'WILD · PENALTY':'SPECIAL ACTION'}</small></div>}</motion.button>});
function PenaltyModal({penalty,userId,teams,countdown,send}:{penalty:any;userId:string;teams:Team[];countdown:number;send:(t:string,e?:any)=>void}){
 const [choice,setChoice]=useState('');
 const attacker=penalty.attackerId===userId;
 const defender=penalty.defenderId===userId;
 let body:any;
 if(penalty.phase==='defender-decision' && defender) body=<><p>You have a Goalkeeper in the slot. Defend this penalty?</p><div className="modal-actions"><button className="primary" onClick={()=>send('attemptSave',{accept:true})}>🧤 Save</button><button className="secondary" onClick={()=>send('attemptSave',{accept:false})}>Decline</button></div></>;
 else if(penalty.phase==='attacker-choosing' && attacker) body=<><p>Pick the Team. Your choice stays hidden from the defender.</p><TeamGrid teams={teams} selected={choice} setSelected={setChoice}/><button className="primary full" disabled={!choice} onClick={()=>send('chooseTeam',{teamId:choice})}>Lock Team</button></>;
 else if(penalty.phase==='defender-guessing' && defender) body=<><div className="countdown">{countdown.toFixed(1)}<small>SECONDS</small></div><p>Which Team did the attacker choose?</p><TeamGrid teams={teams} selected={choice} setSelected={setChoice}/><button className="primary full" disabled={!choice} onClick={()=>send('guessTeam',{teamId:choice})}>Make Guess</button></>;
 else body=<div className="waiting"><div className="spinner"/><p>Waiting for the other player…</p></div>;
 const title=penalty.phase==='defender-decision'?'Goalkeeper decision':penalty.phase==='attacker-choosing'?'Choose your Team':'SAVE — GUESS THE TEAM';
 return <div className="modal-backdrop"><motion.div initial={{scale:.9,opacity:0}} animate={{scale:1,opacity:1}} className="penalty-modal glass"><div className="whistle">⚽</div><span className="eyebrow">PENALTY CHALLENGE</span><h3>{title}</h3>{body}</motion.div></div>;
}
function TeamGrid({teams,selected,setSelected}:{teams:Team[];selected:string;setSelected:(x:string)=>void}){return <div className="team-grid">{teams.map(t=><button key={t.id} className={selected===t.id?'selected':''} onClick={()=>setSelected(t.id)} style={{'--team':t.color} as any}><span>{t.name}</span><b>{t.name.slice(0,1)}</b></button>)}</div>}
function SwitchModal({state,userId,players,me,send,selectedOwn,setSelectedOwn}:{state:any;userId:string;players:any[];me:any;send:(t:string,e?:any)=>void;selectedOwn?:string;setSelectedOwn:(x:string)=>void}){const mine=state.playerId===userId;const target=state.targetPlayerId===userId;const targetPlayer=players.find(p=>p.id===state.targetPlayerId);const [selectedTarget,setSelectedTarget]=useState<string>();return <div className="modal-backdrop"><motion.div initial={{y:20,opacity:0}} animate={{y:0,opacity:1}} className="glass switch-modal"><span className="eyebrow">SWITCH · 1 CARD</span><h3>{mine?'Choose the exchange':'A Switch is being resolved'}</h3>{mine?<><p>Choose exactly one card from your hand and exactly one card from the next player.</p><div className="switch-section"><strong>Your card</strong><div className="mini-hand">{me.hand.map((c:Card)=><button className={selectedOwn===c.id?'selected':''} key={c.id} onClick={()=>setSelectedOwn(c.id)}>{c.type==='number'?c.number:c.type.toUpperCase()}</button>)}</div></div><div className="switch-section"><strong>{targetPlayer?.username}'s card</strong><div className="mini-hand">{(state.targetHand||[]).map((c:Card)=><button className={selectedTarget===c.id?'selected':''} key={c.id} onClick={()=>setSelectedTarget(c.id)}>{c.type==='number'?c.number:c.type.toUpperCase()}</button>)}</div></div><button className="primary full" disabled={!selectedOwn||!selectedTarget} onClick={()=>send('switchCards',{ownCardId:selectedOwn,targetCardId:selectedTarget})}>Confirm Exchange</button><button className="ghost full" onClick={()=>send('passSwitch')}>Pass</button></>:target?<p>{targetPlayer?.username} is choosing one card from each hand.</p>:<div className="waiting"><div className="spinner"/><p>Waiting…</p></div>}</motion.div></div>}
function ResultOverlay({state}:{state:GameState}){return <div className="modal-backdrop"><motion.div initial={{scale:.8,opacity:0}} animate={{scale:1,opacity:1}} className="result-modal glass"><div className="trophy">🏆</div><span className="eyebrow">MATCH FINISHED</span><h3>Final Ranking</h3><div className="ranking">{state.finishedRanking.map((r:any,i)=><div key={r.playerId} className="rank-row"><b>{r.rank===1?'🥇':r.rank===2?'🥈':r.rank===3?'🥉':'#'+r.rank}</b><span>{state.players.find(p=>p.id===r.playerId)?.username}</span><strong>+{r.scoreEarned}</strong></div>)}</div></motion.div></div>}
function createRootApp(){createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>)}createRootApp();
