PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS users (
 id TEXT PRIMARY KEY,
 username TEXT NOT NULL UNIQUE,
 password_hash TEXT NOT NULL,
 score INTEGER NOT NULL DEFAULT 0,
 wins INTEGER NOT NULL DEFAULT 0,
 losses INTEGER NOT NULL DEFAULT 0,
 matches_played INTEGER NOT NULL DEFAULT 0,
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS matches (
 id TEXT PRIMARY KEY,
 status TEXT NOT NULL,
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 finished_at TEXT,
 winner_user_id TEXT,
 FOREIGN KEY (winner_user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS match_players (
 match_id TEXT NOT NULL,
 user_id TEXT NOT NULL,
 rank INTEGER,
 score_earned INTEGER NOT NULL DEFAULT 0,
 cards_remaining INTEGER NOT NULL DEFAULT 0,
 warnings INTEGER NOT NULL DEFAULT 0,
 reds INTEGER NOT NULL DEFAULT 0,
 number_sum INTEGER NOT NULL DEFAULT 0,
 PRIMARY KEY(match_id,user_id),
 FOREIGN KEY(match_id) REFERENCES matches(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS match_events (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 match_id TEXT NOT NULL,
 event_type TEXT NOT NULL,
 actor_user_id TEXT,
 payload_json TEXT NOT NULL,
 created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(match_id) REFERENCES matches(id) ON DELETE CASCADE
);
